<?php
/**
 * hCaptcha Protection Module
 * Add spam protection to forms using hCaptcha service
 * 
 * Generated by PhPstrap Installer
 * Version: 1.0.0
 */

class HcaptchaModule extends BaseModule {
    
    public function init() {
        // Module initialization
        // This method is called when the module is loaded
    }
    
    public function renderCaptcha($data) {
        $site_key = $this->getSetting('site_key', '');
        if (empty($site_key) || !$this->getSetting('enabled', false)) {
            return $data;
        }
        
        $html = '<div class="h-captcha" data-sitekey="' . htmlspecialchars($site_key) . '"></div>';
        $html .= '<script src="https://js.hcaptcha.com/1/api.js" async defer></script>';
        
        return $data . $html;
    }
    
    public function validateCaptcha($data) {
        if (!$this->getSetting('enabled', false)) {
            return $data;
        }
        
        $secret_key = $this->getSetting('secret_key', '');
        $response = $_POST['h-captcha-response'] ?? '';
        
        if (empty($secret_key) || empty($response)) {
            $data['errors'][] = 'Captcha verification required.';
            return $data;
        }
        
        // Verify with hCaptcha API
        $verify_url = 'https://api.hcaptcha.com/siteverify';
        $post_data = http_build_query([
            'secret' => $secret_key,
            'response' => $response
        ]);
        
        $context = stream_context_create([
            'http' => [
                'method' => 'POST',
                'header' => 'Content-Type: application/x-www-form-urlencoded',
                'content' => $post_data
            ]
        ]);
        
        $result = file_get_contents($verify_url, false, $context);
        $response_data = json_decode($result, true);
        
        if (!$response_data['success']) {
            $data['errors'][] = 'Captcha verification failed.';
        }
        
        return $data;
    }
}
?>