<?php
/**
 * phpStrapMaintenance Page
 * Generated by installer on 2025-09-10 22:15:25
 */

if (!defined('MAINTENANCE_MODE') || !MAINTENANCE_MODE) { header('Location: /'); exit; }

header('HTTP/1.1 503 Service Temporarily Unavailable');
header('Status: 503 Service Temporarily Unavailable');
header('Retry-After: 3600');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site Maintenance - BootPHP</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
        .container { text-align: center; max-width: 600px; padding: 2rem; }
        .icon { font-size: 4rem; margin-bottom: 1rem; }
        h1 { font-size: 2.5rem; margin-bottom: 1rem; }
        p { font-size: 1.2rem; margin-bottom: 2rem; opacity: 0.9; }
        .back-link { display: inline-block; padding: 0.75rem 1.5rem; background: rgba(255,255,255,0.2); border-radius: 0.5rem; text-decoration: none; color: white; transition: background 0.3s ease; }
        .back-link:hover { background: rgba(255,255,255,0.3); }
    </style>
</head>
<body>
    <div class="container">
        <div class="icon">🔧</div>
        <h1>Site Under Maintenance</h1>
        <p><?php echo defined('MAINTENANCE_MESSAGE') ? MAINTENANCE_MESSAGE : 'We are currently performing scheduled maintenance. Please check back soon.'; ?></p>
        <a href="#" onclick="location.reload()" class="back-link">Refresh Page</a>
    </div>
</body>
</html>