<?php
/**
 * Analytics Tracking Module
 * Google Analytics and Facebook Pixel integration
 * 
 * Generated by PhPstrap Installer
 * Version: 1.0.0
 */

class AnalyticsModule extends BaseModule {
    
    public function init() {
        // Module initialization
        // This method is called when the module is loaded
    }
    
    public function renderHeadTags($data) {
        if (!$this->getSetting('enabled', false)) {
            return $data;
        }
        
        $html = '';
        
        // Google Analytics
        $ga_id = $this->getSetting('google_analytics_id', '');
        if (!empty($ga_id)) {
            $html .= "<script async src='https://www.googletagmanager.com/gtag/js?id={$ga_id}'></script>";
            $html .= "<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','{$ga_id}');</script>";
        }
        
        // Facebook Pixel
        $fb_id = $this->getSetting('facebook_pixel_id', '');
        if (!empty($fb_id)) {
            $html .= "<script>!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','{$fb_id}');fbq('track','PageView');</script>";
        }
        
        return $data . $html;
    }
}
?>