<?php
/**
 * phpStrapEnglish Language File
 * Generated by installer on 2025-10-14 02:54:27
 */

$lang = [
    // Common
    'yes' => 'Yes',
    'no' => 'No',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'create' => 'Create',
    'update' => 'Update',
    'submit' => 'Submit',
    'reset' => 'Reset',
    'back' => 'Back',
    'next' => 'Next',
    'previous' => 'Previous',
    'continue' => 'Continue',
    'loading' => 'Loading...',
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Information',

    // Authentication
    'login' => 'Login',
    'logout' => 'Logout',
    'register' => 'Register',
    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'forgot_password' => 'Forgot Password?',
    'reset_password' => 'Reset Password',
    'remember_me' => 'Remember Me',
    'login_required' => 'Login required to access this page',
    'invalid_credentials' => 'Invalid email or password',
    'account_locked' => 'Account temporarily locked due to failed login attempts',
    'email_not_verified' => 'Please verify your email address before logging in',

    // User Management
    'user' => 'User',
    'users' => 'Users',
    'profile' => 'Profile',
    'account' => 'Account',
    'name' => 'Name',
    'username' => 'Username',
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'phone' => 'Phone',
    'address' => 'Address',
    'city' => 'City',
    'country' => 'Country',
    'timezone' => 'Timezone',
    'language' => 'Language',

    // Forms and Validation
    'required_field' => 'This field is required',
    'invalid_email' => 'Please enter a valid email address',
    'password_too_short' => 'Password must be at least 8 characters long',
    'passwords_do_not_match' => 'Passwords do not match',
    'invalid_phone' => 'Please enter a valid phone number',
    'file_too_large' => 'File size exceeds maximum limit',
    'invalid_file_type' => 'File type not allowed',

    // Dashboard and Navigation
    'dashboard' => 'Dashboard',
    'admin_panel' => 'Admin Panel',
    'settings' => 'Settings',
    'modules' => 'Modules',
    'reports' => 'Reports',
    'statistics' => 'Statistics',
    'home' => 'Home',
    'menu' => 'Menu',
    'navigation' => 'Navigation',

    // Membership and Credits
    'membership' => 'Membership',
    'credits' => 'Credits',
    'balance' => 'Balance',
    'purchase' => 'Purchase',
    'transaction' => 'Transaction',
    'transactions' => 'Transactions',
    'withdraw' => 'Withdraw',
    'withdrawal' => 'Withdrawal',
    'affiliate' => 'Affiliate',
    'referral' => 'Referral',
    'commission' => 'Commission',

    // Status Messages
    'saved_successfully' => 'Settings saved successfully',
    'updated_successfully' => 'Updated successfully',
    'deleted_successfully' => 'Deleted successfully',
    'created_successfully' => 'Created successfully',
    'operation_failed' => 'Operation failed. Please try again.',
    'permission_denied' => 'Permission denied',
    'not_found' => 'Page not found',
    'server_error' => 'Server error. Please try again later.',

    // Date and Time
    'date' => 'Date',
    'time' => 'Time',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',
    'last_login' => 'Last Login',
    'expires_at' => 'Expires At',

    // Email Templates
    'email_verification_subject' => 'Verify Your Email Address',
    'password_reset_subject' => 'Password Reset Request',
    'welcome_subject' => 'Welcome to ' . SITE_NAME,
    'email_footer' => 'This is an automated message from ' . SITE_NAME,
];

function __($key, $default = null) { global $lang; return $lang[$key] ?? ($default ?: $key); }
function sprintf__($key, ...$args) { return sprintf(__($key), ...$args); }
?>