<?php
/**
 * BootPHP Installer - Configuration Generation Functions
 * Save as: installer/config.php
 */

function generateDatabaseConfig($db_config) {
    $config = "<?php\n";
    $config .= "/**\n";
    $config .= " * BootPHP Database Configuration\n";
    $config .= " * Generated by installer on " . date('Y-m-d H:i:s') . "\n";
    $config .= " */\n\n";
    
    $config .= "// Database configuration\n";
    $config .= "define('DB_HOST', '" . addslashes($db_config['host']) . "');\n";
    $config .= "define('DB_NAME', '" . addslashes($db_config['name']) . "');\n";
    $config .= "define('DB_USER', '" . addslashes($db_config['user']) . "');\n";
    $config .= "define('DB_PASS', '" . addslashes($db_config['pass']) . "');\n";
    $config .= "define('DB_PORT', " . (int)$db_config['port'] . ");\n";
    $config .= "define('DB_CHARSET', 'utf8mb4');\n\n";
    
    $config .= "// PDO DSN\n";
    $config .= "define('DB_DSN', 'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET);\n\n";
    
    $config .= "// PDO Options\n";
    $config .= "define('DB_OPTIONS', [\n";
    $config .= "    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,\n";
    $config .= "    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n";
    $config .= "    PDO::ATTR_EMULATE_PREPARES => false,\n";
    $config .= "    PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4'\n";
    $config .= "]);\n\n";
    
    $config .= "// Database connection function\n";
    $config .= "function getDbConnection() {\n";
    $config .= "    static \$pdo = null;\n";
    $config .= "    \n";
    $config .= "    if (\$pdo === null) {\n";
    $config .= "        try {\n";
    $config .= "            \$pdo = new PDO(DB_DSN, DB_USER, DB_PASS, DB_OPTIONS);\n";
    $config .= "        } catch (PDOException \$e) {\n";
    $config .= "            error_log('Database connection failed: ' . \$e->getMessage());\n";
    $config .= "            throw new Exception('Database connection failed');\n";
    $config .= "        }\n";
    $config .= "    }\n";
    $config .= "    \n";
    $config .= "    return \$pdo;\n";
    $config .= "}\n\n";
    
    $config .= "// Test database connection\n";
    $config .= "function testDbConnection() {\n";
    $config .= "    try {\n";
    $config .= "        \$pdo = getDbConnection();\n";
    $config .= "        \$stmt = \$pdo->query('SELECT 1');\n";
    $config .= "        return true;\n";
    $config .= "    } catch (Exception \$e) {\n";
    $config .= "        return false;\n";
    $config .= "    }\n";
    $config .= "}\n";
    $config .= "?>";
    
    return $config;
}

function generateAppConfig($site_name) {
    $config = "<?php\n";
    $config .= "/**\n";
    $config .= " * BootPHP Application Configuration\n";
    $config .= " * Generated by installer on " . date('Y-m-d H:i:s') . "\n";
    $config .= " */\n\n";
    
    // Core application settings
    $config .= "// Core Application Settings\n";
    $config .= "define('BOOTPHP_VERSION', '1.0.0');\n";
    $config .= "define('SITE_NAME', '" . addslashes($site_name) . "');\n";
    $config .= "define('BASE_PATH', dirname(__DIR__));\n";
    $config .= "define('BASE_URL', getBaseUrl());\n";
    $config .= "define('TIMEZONE', 'UTC');\n\n";
    
    // Security settings
    $config .= "// Security Settings\n";
    $config .= "define('SECURITY_SALT', '" . generateSecuritySalt() . "');\n";
    $config .= "define('SESSION_NAME', 'bootphp_session');\n";
    $config .= "define('SESSION_LIFETIME', 3600);\n";
    $config .= "define('CSRF_TOKEN_NAME', 'bootphp_csrf_token');\n";
    $config .= "define('API_RATE_LIMIT', 1000);\n";
    $config .= "define('API_RATE_WINDOW', 3600);\n\n";
    
    // File and upload settings
    $config .= "// File and Upload Settings\n";
    $config .= "define('UPLOAD_PATH', BASE_PATH . '/uploads');\n";
    $config .= "define('UPLOAD_URL', BASE_URL . '/uploads');\n";
    $config .= "define('MAX_UPLOAD_SIZE', 10485760); // 10MB\n";
    $config .= "define('ALLOWED_EXTENSIONS', 'jpg,jpeg,png,gif,pdf,doc,docx,txt,zip');\n\n";
    
    // Cache and performance
    $config .= "// Cache and Performance\n";
    $config .= "define('CACHE_ENABLED', false);\n";
    $config .= "define('CACHE_LIFETIME', 3600);\n";
    $config .= "define('DEBUG_MODE', false);\n";
    $config .= "define('LOG_ERRORS', true);\n";
    $config .= "define('LOG_PATH', BASE_PATH . '/logs');\n\n";
    
    // Email settings
    $config .= "// Email Settings\n";
    $config .= "define('MAIL_DRIVER', 'php'); // php, smtp\n";
    $config .= "define('MAIL_FROM_ADDRESS', '');\n";
    $config .= "define('MAIL_FROM_NAME', SITE_NAME);\n\n";
    
    // Helper functions
    $config .= "// Helper Functions\n";
    $config .= "function getBaseUrl() {\n";
    $config .= "    \$protocol = isset(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] === 'on' ? 'https' : 'http';\n";
    $config .= "    \$host = \$_SERVER['HTTP_HOST'] ?? 'localhost';\n";
    $config .= "    \$dir = rtrim(dirname(\$_SERVER['SCRIPT_NAME']), '/');\n";
    $config .= "    return \$protocol . '://' . \$host . \$dir;\n";
    $config .= "}\n\n";
    
    $config .= "function generateCsrfToken() {\n";
    $config .= "    if (!isset(\$_SESSION[CSRF_TOKEN_NAME])) {\n";
    $config .= "        \$_SESSION[CSRF_TOKEN_NAME] = bin2hex(random_bytes(32));\n";
    $config .= "    }\n";
    $config .= "    return \$_SESSION[CSRF_TOKEN_NAME];\n";
    $config .= "}\n\n";
    
    $config .= "function validateCsrfToken(\$token) {\n";
    $config .= "    return isset(\$_SESSION[CSRF_TOKEN_NAME]) && hash_equals(\$_SESSION[CSRF_TOKEN_NAME], \$token);\n";
    $config .= "}\n\n";
    
    $config .= "function logError(\$message, \$context = []) {\n";
    $config .= "    if (LOG_ERRORS) {\n";
    $config .= "        \$log_file = LOG_PATH . '/error_' . date('Y-m-d') . '.log';\n";
    $config .= "        \$timestamp = date('Y-m-d H:i:s');\n";
    $config .= "        \$log_entry = \"[\$timestamp] \$message\";\n";
    $config .= "        if (!empty(\$context)) {\n";
    $config .= "            \$log_entry .= ' Context: ' . json_encode(\$context);\n";
    $config .= "        }\n";
    $config .= "        \$log_entry .= PHP_EOL;\n";
    $config .= "        file_put_contents(\$log_file, \$log_entry, FILE_APPEND | LOCK_EX);\n";
    $config .= "    }\n";
    $config .= "}\n\n";
    
    $config .= "// Initialize application\n";
    $config .= "function initializeApp() {\n";
    $config .= "    // Set timezone\n";
    $config .= "    date_default_timezone_set(TIMEZONE);\n";
    $config .= "    \n";
    $config .= "    // Configure session\n";
    $config .= "    ini_set('session.name', SESSION_NAME);\n";
    $config .= "    ini_set('session.gc_maxlifetime', SESSION_LIFETIME);\n";
    $config .= "    ini_set('session.cookie_httponly', 1);\n";
    $config .= "    ini_set('session.cookie_secure', isset(\$_SERVER['HTTPS']));\n";
    $config .= "    \n";
    $config .= "    // Start session if not already started\n";
    $config .= "    if (session_status() === PHP_SESSION_NONE) {\n";
    $config .= "        session_start();\n";
    $config .= "    }\n";
    $config .= "    \n";
    $config .= "    // Set error reporting based on debug mode\n";
    $config .= "    if (DEBUG_MODE) {\n";
    $config .= "        error_reporting(E_ALL);\n";
    $config .= "        ini_set('display_errors', 1);\n";
    $config .= "    } else {\n";
    $config .= "        error_reporting(E_ALL & ~E_NOTICE);\n";
    $config .= "        ini_set('display_errors', 0);\n";
    $config .= "    }\n";
    $config .= "}\n";
    $config .= "?>";
    
    return $config;
}

function generateSettingsHelper() {
    $helper = "<?php\n";
    $helper .= "/**\n";
    $helper .= " * BootPHP Settings Helper\n";
    $helper .= " * Manages application settings from database\n";
    $helper .= " * Generated by installer on " . date('Y-m-d H:i:s') . "\n";
    $helper .= " */\n\n";
    
    $helper .= "class Settings {\n";
    $helper .= "    private static \$cache = [];\n";
    $helper .= "    private static \$loaded = false;\n\n";
    
    $helper .= "    /**\n";
    $helper .= "     * Get setting value\n";
    $helper .= "     */\n";
    $helper .= "    public static function get(\$key, \$default = null) {\n";
    $helper .= "        if (!self::\$loaded) {\n";
    $helper .= "            self::loadSettings();\n";
    $helper .= "        }\n";
    $helper .= "        \n";
    $helper .= "        return isset(self::\$cache[\$key]) ? self::\$cache[\$key] : \$default;\n";
    $helper .= "    }\n\n";
    
    $helper .= "    /**\n";
    $helper .= "     * Set setting value\n";
    $helper .= "     */\n";
    $helper .= "    public static function set(\$key, \$value, \$type = 'string') {\n";
    $helper .= "        try {\n";
    $helper .= "            \$pdo = getDbConnection();\n";
    $helper .= "            \n";
    $helper .= "            \$stmt = \$pdo->prepare(\"\n";
    $helper .= "                INSERT INTO settings (`key`, `value`, `type`, updated_at) \n";
    $helper .= "                VALUES (?, ?, ?, NOW()) \n";
    $helper .= "                ON DUPLICATE KEY UPDATE \n";
    $helper .= "                `value` = VALUES(`value`), \n";
    $helper .= "                `type` = VALUES(`type`), \n";
    $helper .= "                updated_at = NOW()\n";
    $helper .= "            \");\n";
    $helper .= "            \n";
    $helper .= "            \$stmt->execute([\$key, \$value, \$type]);\n";
    $helper .= "            \n";
    $helper .= "            // Update cache\n";
    $helper .= "            self::\$cache[\$key] = self::castValue(\$value, \$type);\n";
    $helper .= "            \n";
    $helper .= "            return true;\n";
    $helper .= "        } catch (Exception \$e) {\n";
    $helper .= "            logError('Failed to set setting: ' . \$e->getMessage(), ['key' => \$key, 'value' => \$value]);\n";
    $helper .= "            return false;\n";
    $helper .= "        }\n";
    $helper .= "    }\n\n";
    
    $helper .= "    /**\n";
    $helper .= "     * Load all settings from database\n";
    $helper .= "     */\n";
    $helper .= "    private static function loadSettings() {\n";
    $helper .= "        try {\n";
    $helper .= "            \$pdo = getDbConnection();\n";
    $helper .= "            \$stmt = \$pdo->query('SELECT `key`, `value`, `type` FROM settings');\n";
    $helper .= "            \$settings = \$stmt->fetchAll();\n";
    $helper .= "            \n";
    $helper .= "            foreach (\$settings as \$setting) {\n";
    $helper .= "                self::\$cache[\$setting['key']] = self::castValue(\$setting['value'], \$setting['type']);\n";
    $helper .= "            }\n";
    $helper .= "            \n";
    $helper .= "            self::\$loaded = true;\n";
    $helper .= "        } catch (Exception \$e) {\n";
    $helper .= "            logError('Failed to load settings: ' . \$e->getMessage());\n";
    $helper .= "            self::\$loaded = true; // Prevent infinite retry\n";
    $helper .= "        }\n";
    $helper .= "    }\n\n";
    
    $helper .= "    /**\n";
    $helper .= "     * Cast value to appropriate type\n";
    $helper .= "     */\n";
    $helper .= "    private static function castValue(\$value, \$type) {\n";
    $helper .= "        switch (\$type) {\n";
    $helper .= "            case 'boolean':\n";
    $helper .= "                return (bool)\$value;\n";
    $helper .= "            case 'integer':\n";
    $helper .= "                return (int)\$value;\n";
    $helper .= "            case 'json':\n";
    $helper .= "                return json_decode(\$value, true);\n";
    $helper .= "            case 'array':\n";
    $helper .= "                return explode(',', \$value);\n";
    $helper .= "            default:\n";
    $helper .= "                return \$value;\n";
    $helper .= "        }\n";
    $helper .= "    }\n\n";
    
    $helper .= "    /**\n";
    $helper .= "     * Get all settings\n";
    $helper .= "     */\n";
    $helper .= "    public static function getAll() {\n";
    $helper .= "        if (!self::\$loaded) {\n";
    $helper .= "            self::loadSettings();\n";
    $helper .= "        }\n";
    $helper .= "        \n";
    $helper .= "        return self::\$cache;\n";
    $helper .= "    }\n\n";
    
    $helper .= "    /**\n";
    $helper .= "     * Clear settings cache\n";
    $helper .= "     */\n";
    $helper .= "    public static function clearCache() {\n";
    $helper .= "        self::\$cache = [];\n";
    $helper .= "        self::\$loaded = false;\n";
    $helper .= "    }\n\n";
    
    $helper .= "    /**\n";
    $helper .= "     * Get settings by category\n";
    $helper .= "     */\n";
    $helper .= "    public static function getByCategory(\$category) {\n";
    $helper .= "        try {\n";
    $helper .= "            \$pdo = getDbConnection();\n";
    $helper .= "            \$stmt = \$pdo->prepare('SELECT `key`, `value`, `type` FROM settings WHERE category = ?');\n";
    $helper .= "            \$stmt->execute([\$category]);\n";
    $helper .= "            \$settings = \$stmt->fetchAll();\n";
    $helper .= "            \n";
    $helper .= "            \$result = [];\n";
    $helper .= "            foreach (\$settings as \$setting) {\n";
    $helper .= "                \$result[\$setting['key']] = self::castValue(\$setting['value'], \$setting['type']);\n";
    $helper .= "            }\n";
    $helper .= "            \n";
    $helper .= "            return \$result;\n";
    $helper .= "        } catch (Exception \$e) {\n";
    $helper .= "            logError('Failed to get settings by category: ' . \$e->getMessage(), ['category' => \$category]);\n";
    $helper .= "            return [];\n";
    $helper .= "        }\n";
    $helper .= "    }\n";
    $helper .= "}\n\n";
    
    $helper .= "// Convenience functions\n";
    $helper .= "function getSetting(\$key, \$default = null) {\n";
    $helper .= "    return Settings::get(\$key, \$default);\n";
    $helper .= "}\n\n";
    
    $helper .= "function setSetting(\$key, \$value, \$type = 'string') {\n";
    $helper .= "    return Settings::set(\$key, \$value, \$type);\n";
    $helper .= "}\n";
    $helper .= "?>";
    
    return $helper;
}

function generateModulesSystem() {
    $system = "<?php\n";
    $system .= "/**\n";
    $system .= " * BootPHP Modules System\n";
    $system .= " * Handles module loading and hook execution\n";
    $system .= " * Generated by installer on " . date('Y-m-d H:i:s') . "\n";
    $system .= " */\n\n";
    
    // Base Module Class
    $system .= "/**\n";
    $system .= " * Base Module Class\n";
    $system .= " * All modules should extend this class\n";
    $system .= " */\n";
    $system .= "abstract class BaseModule {\n";
    $system .= "    protected \$name;\n";
    $system .= "    protected \$settings;\n";
    $system .= "    protected \$enabled;\n\n";
    
    $system .= "    public function __construct(\$name, \$settings = [], \$enabled = false) {\n";
    $system .= "        \$this->name = \$name;\n";
    $system .= "        \$this->settings = \$settings;\n";
    $system .= "        \$this->enabled = \$enabled;\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Module initialization - override in child classes\n";
    $system .= "     */\n";
    $system .= "    public function init() {\n";
    $system .= "        // Override in child classes\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Get module setting\n";
    $system .= "     */\n";
    $system .= "    protected function getSetting(\$key, \$default = null) {\n";
    $system .= "        return isset(\$this->settings[\$key]) ? \$this->settings[\$key] : \$default;\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Update module setting\n";
    $system .= "     */\n";
    $system .= "    protected function setSetting(\$key, \$value) {\n";
    $system .= "        \$this->settings[\$key] = \$value;\n";
    $system .= "        return ModuleManager::updateModuleSetting(\$this->name, \$key, \$value);\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Check if module is enabled\n";
    $system .= "     */\n";
    $system .= "    public function isEnabled() {\n";
    $system .= "        return \$this->enabled;\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Get module name\n";
    $system .= "     */\n";
    $system .= "    public function getName() {\n";
    $system .= "        return \$this->name;\n";
    $system .= "    }\n";
    $system .= "}\n\n";
    
    // Module Manager Class
    $system .= "/**\n";
    $system .= " * Module Manager Class\n";
    $system .= " * Manages module loading, enabling/disabling, and hook execution\n";
    $system .= " */\n";
    $system .= "class ModuleManager {\n";
    $system .= "    private static \$modules = [];\n";
    $system .= "    private static \$hooks = [];\n";
    $system .= "    private static \$loaded = false;\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Load all enabled modules\n";
    $system .= "     */\n";
    $system .= "    public static function loadModules() {\n";
    $system .= "        if (self::\$loaded) {\n";
    $system .= "            return;\n";
    $system .= "        }\n\n";
    
    $system .= "        try {\n";
    $system .= "            \$pdo = getDbConnection();\n";
    $system .= "            \$stmt = \$pdo->query('\n";
    $system .= "                SELECT name, title, settings, hooks, enabled \n";
    $system .= "                FROM modules \n";
    $system .= "                WHERE enabled = 1 \n";
    $system .= "                ORDER BY priority ASC\n";
    $system .= "            ');\n";
    $system .= "            \$modules = \$stmt->fetchAll();\n\n";
    
    $system .= "            foreach (\$modules as \$module_data) {\n";
    $system .= "                self::loadModule(\$module_data);\n";
    $system .= "            }\n\n";
    
    $system .= "            self::\$loaded = true;\n";
    $system .= "        } catch (Exception \$e) {\n";
    $system .= "            logError('Failed to load modules: ' . \$e->getMessage());\n";
    $system .= "        }\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Load individual module\n";
    $system .= "     */\n";
    $system .= "    private static function loadModule(\$module_data) {\n";
    $system .= "        \$name = \$module_data['name'];\n";
    $system .= "        \$module_file = BASE_PATH . '/modules/' . \$name . '/' . \$name . '.php';\n\n";
    
    $system .= "        if (!file_exists(\$module_file)) {\n";
    $system .= "            logError('Module file not found: ' . \$module_file);\n";
    $system .= "            return false;\n";
    $system .= "        }\n\n";
    
    $system .= "        try {\n";
    $system .= "            require_once \$module_file;\n\n";
    
    $system .= "            \$class_name = ucfirst(\$name) . 'Module';\n";
    $system .= "            if (!class_exists(\$class_name)) {\n";
    $system .= "                logError('Module class not found: ' . \$class_name);\n";
    $system .= "                return false;\n";
    $system .= "            }\n\n";
    
    $system .= "            \$settings = json_decode(\$module_data['settings'], true) ?: [];\n";
    $system .= "            \$module = new \$class_name(\$name, \$settings, true);\n";
    $system .= "            \$module->init();\n\n";
    
    $system .= "            self::\$modules[\$name] = \$module;\n\n";
    
    $system .= "            // Register hooks\n";
    $system .= "            \$hooks = json_decode(\$module_data['hooks'], true) ?: [];\n";
    $system .= "            foreach (\$hooks as \$hook_name => \$hook_methods) {\n";
    $system .= "                if (!isset(self::\$hooks[\$hook_name])) {\n";
    $system .= "                    self::\$hooks[\$hook_name] = [];\n";
    $system .= "                }\n\n";
    
    $system .= "                foreach (\$hook_methods as \$hook_method) {\n";
    $system .= "                    self::\$hooks[\$hook_name][] = [\n";
    $system .= "                        'module' => \$module,\n";
    $system .= "                        'method' => \$hook_method['method'],\n";
    $system .= "                        'priority' => \$hook_method['priority'] ?? 10\n";
    $system .= "                    ];\n";
    $system .= "                }\n";
    $system .= "            }\n\n";
    
    $system .= "            // Sort hooks by priority\n";
    $system .= "            foreach (self::\$hooks as \$hook_name => \$hook_list) {\n";
    $system .= "                usort(self::\$hooks[\$hook_name], function(\$a, \$b) {\n";
    $system .= "                    return \$a['priority'] <=> \$b['priority'];\n";
    $system .= "                });\n";
    $system .= "            }\n\n";
    
    $system .= "            return true;\n";
    $system .= "        } catch (Exception \$e) {\n";
    $system .= "            logError('Failed to load module: ' . \$name . ' - ' . \$e->getMessage());\n";
    $system .= "            return false;\n";
    $system .= "        }\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Execute hook\n";
    $system .= "     */\n";
    $system .= "    public static function executeHook(\$hook_name, \$data = null) {\n";
    $system .= "        if (!self::\$loaded) {\n";
    $system .= "            self::loadModules();\n";
    $system .= "        }\n\n";
    
    $system .= "        if (!isset(self::\$hooks[\$hook_name])) {\n";
    $system .= "            return \$data;\n";
    $system .= "        }\n\n";
    
    $system .= "        foreach (self::\$hooks[\$hook_name] as \$hook) {\n";
    $system .= "            try {\n";
    $system .= "                \$module = \$hook['module'];\n";
    $system .= "                \$method = \$hook['method'];\n\n";
    
    $system .= "                if (method_exists(\$module, \$method)) {\n";
    $system .= "                    \$data = \$module->\$method(\$data);\n";
    $system .= "                }\n";
    $system .= "            } catch (Exception \$e) {\n";
    $system .= "                logError('Hook execution failed: ' . \$hook_name . ' - ' . \$e->getMessage());\n";
    $system .= "            }\n";
    $system .= "        }\n\n";
    
    $system .= "        return \$data;\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Get loaded module\n";
    $system .= "     */\n";
    $system .= "    public static function getModule(\$name) {\n";
    $system .= "        return isset(self::\$modules[\$name]) ? self::\$modules[\$name] : null;\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Get all loaded modules\n";
    $system .= "     */\n";
    $system .= "    public static function getModules() {\n";
    $system .= "        return self::\$modules;\n";
    $system .= "    }\n\n";
    
    $system .= "    /**\n";
    $system .= "     * Update module setting in database\n";
    $system .= "     */\n";
    $system .= "    public static function updateModuleSetting(\$module_name, \$key, \$value) {\n";
    $system .= "        try {\n";
    $system .= "            \$pdo = getDbConnection();\n";
    $system .= "            \$stmt = \$pdo->prepare('SELECT settings FROM modules WHERE name = ?');\n";
    $system .= "            \$stmt->execute([\$module_name]);\n";
    $system .= "            \$settings_json = \$stmt->fetchColumn();\n\n";
    
    $system .= "            \$settings = json_decode(\$settings_json, true) ?: [];\n";
    $system .= "            \$settings[\$key] = \$value;\n\n";
    
    $system .= "            \$stmt = \$pdo->prepare('UPDATE modules SET settings = ? WHERE name = ?');\n";
    $system .= "            return \$stmt->execute([json_encode(\$settings), \$module_name]);\n";
    $system .= "        } catch (Exception \$e) {\n";
    $system .= "            logError('Failed to update module setting: ' . \$e->getMessage());\n";
    $system .= "            return false;\n";
    $system .= "        }\n";
    $system .= "    }\n";
    $system .= "}\n\n";
    
    $system .= "// Convenience function for executing hooks\n";
    $system .= "function executeHook(\$hook_name, \$data = null) {\n";
    $system .= "    return ModuleManager::executeHook(\$hook_name, \$data);\n";
    $system .= "}\n";
    $system .= "?>";
    
    return $system;
}

function generateLanguageFile() {
    $lang = "<?php\n";
    $lang .= "/**\n";
    $lang .= " * BootPHP English Language File\n";
    $lang .= " * Generated by installer on " . date('Y-m-d H:i:s') . "\n";
    $lang .= " */\n\n";
    
    $lang .= "\$lang = [\n";
    
    // Common terms
    $lang .= "    // Common\n";
    $lang .= "    'yes' => 'Yes',\n";
    $lang .= "    'no' => 'No',\n";
    $lang .= "    'save' => 'Save',\n";
    $lang .= "    'cancel' => 'Cancel',\n";
    $lang .= "    'delete' => 'Delete',\n";
    $lang .= "    'edit' => 'Edit',\n";
    $lang .= "    'create' => 'Create',\n";
    $lang .= "    'update' => 'Update',\n";
    $lang .= "    'submit' => 'Submit',\n";
    $lang .= "    'reset' => 'Reset',\n";
    $lang .= "    'back' => 'Back',\n";
    $lang .= "    'next' => 'Next',\n";
    $lang .= "    'previous' => 'Previous',\n";
    $lang .= "    'continue' => 'Continue',\n";
    $lang .= "    'loading' => 'Loading...',\n";
    $lang .= "    'success' => 'Success',\n";
    $lang .= "    'error' => 'Error',\n";
    $lang .= "    'warning' => 'Warning',\n";
    $lang .= "    'info' => 'Information',\n\n";
    
    // Authentication
    $lang .= "    // Authentication\n";
    $lang .= "    'login' => 'Login',\n";
    $lang .= "    'logout' => 'Logout',\n";
    $lang .= "    'register' => 'Register',\n";
    $lang .= "    'email' => 'Email',\n";
    $lang .= "    'password' => 'Password',\n";
    $lang .= "    'confirm_password' => 'Confirm Password',\n";
    $lang .= "    'forgot_password' => 'Forgot Password?',\n";
    $lang .= "    'reset_password' => 'Reset Password',\n";
    $lang .= "    'remember_me' => 'Remember Me',\n";
    $lang .= "    'login_required' => 'Login required to access this page',\n";
    $lang .= "    'invalid_credentials' => 'Invalid email or password',\n";
    $lang .= "    'account_locked' => 'Account temporarily locked due to failed login attempts',\n";
    $lang .= "    'email_not_verified' => 'Please verify your email address before logging in',\n\n";
    
    // User management
    $lang .= "    // User Management\n";
    $lang .= "    'user' => 'User',\n";
    $lang .= "    'users' => 'Users',\n";
    $lang .= "    'profile' => 'Profile',\n";
    $lang .= "    'account' => 'Account',\n";
    $lang .= "    'name' => 'Name',\n";
    $lang .= "    'username' => 'Username',\n";
    $lang .= "    'first_name' => 'First Name',\n";
    $lang .= "    'last_name' => 'Last Name',\n";
    $lang .= "    'phone' => 'Phone',\n";
    $lang .= "    'address' => 'Address',\n";
    $lang .= "    'city' => 'City',\n";
    $lang .= "    'country' => 'Country',\n";
    $lang .= "    'timezone' => 'Timezone',\n";
    $lang .= "    'language' => 'Language',\n\n";
    
    // Forms and validation
    $lang .= "    // Forms and Validation\n";
    $lang .= "    'required_field' => 'This field is required',\n";
    $lang .= "    'invalid_email' => 'Please enter a valid email address',\n";
    $lang .= "    'password_too_short' => 'Password must be at least 8 characters long',\n";
    $lang .= "    'passwords_do_not_match' => 'Passwords do not match',\n";
    $lang .= "    'invalid_phone' => 'Please enter a valid phone number',\n";
    $lang .= "    'file_too_large' => 'File size exceeds maximum limit',\n";
    $lang .= "    'invalid_file_type' => 'File type not allowed',\n\n";
    
    // Dashboard and navigation
    $lang .= "    // Dashboard and Navigation\n";
    $lang .= "    'dashboard' => 'Dashboard',\n";
    $lang .= "    'admin_panel' => 'Admin Panel',\n";
    $lang .= "    'settings' => 'Settings',\n";
    $lang .= "    'modules' => 'Modules',\n";
    $lang .= "    'reports' => 'Reports',\n";
    $lang .= "    'statistics' => 'Statistics',\n";
    $lang .= "    'home' => 'Home',\n";
    $lang .= "    'menu' => 'Menu',\n";
    $lang .= "    'navigation' => 'Navigation',\n\n";
    
    // Membership and credits
    $lang .= "    // Membership and Credits\n";
    $lang .= "    'membership' => 'Membership',\n";
    $lang .= "    'credits' => 'Credits',\n";
    $lang .= "    'balance' => 'Balance',\n";
    $lang .= "    'purchase' => 'Purchase',\n";
    $lang .= "    'transaction' => 'Transaction',\n";
    $lang .= "    'transactions' => 'Transactions',\n";
    $lang .= "    'withdraw' => 'Withdraw',\n";
    $lang .= "    'withdrawal' => 'Withdrawal',\n";
    $lang .= "    'affiliate' => 'Affiliate',\n";
    $lang .= "    'referral' => 'Referral',\n";
    $lang .= "    'commission' => 'Commission',\n\n";
    
    // Status messages
    $lang .= "    // Status Messages\n";
    $lang .= "    'saved_successfully' => 'Settings saved successfully',\n";
    $lang .= "    'updated_successfully' => 'Updated successfully',\n";
    $lang .= "    'deleted_successfully' => 'Deleted successfully',\n";
    $lang .= "    'created_successfully' => 'Created successfully',\n";
    $lang .= "    'operation_failed' => 'Operation failed. Please try again.',\n";
    $lang .= "    'permission_denied' => 'Permission denied',\n";
    $lang .= "    'not_found' => 'Page not found',\n";
    $lang .= "    'server_error' => 'Server error. Please try again later.',\n\n";
    
    // Date and time
    $lang .= "    // Date and Time\n";
    $lang .= "    'date' => 'Date',\n";
    $lang .= "    'time' => 'Time',\n";
    $lang .= "    'created_at' => 'Created At',\n";
    $lang .= "    'updated_at' => 'Updated At',\n";
    $lang .= "    'last_login' => 'Last Login',\n";
    $lang .= "    'expires_at' => 'Expires At',\n\n";
    
    // Email templates
    $lang .= "    // Email Templates\n";
    $lang .= "    'email_verification_subject' => 'Verify Your Email Address',\n";
    $lang .= "    'password_reset_subject' => 'Password Reset Request',\n";
    $lang .= "    'welcome_subject' => 'Welcome to ' . SITE_NAME,\n";
    $lang .= "    'email_footer' => 'This is an automated message from ' . SITE_NAME,\n\n";
    
    $lang .= "];\n\n";
    
    $lang .= "// Language function\n";
    $lang .= "function __(\$key, \$default = null) {\n";
    $lang .= "    global \$lang;\n";
    $lang .= "    return isset(\$lang[\$key]) ? \$lang[\$key] : (\$default ?: \$key);\n";
    $lang .= "}\n\n";
    
    $lang .= "// Text formatting function\n";
    $lang .= "function sprintf__(\$key, ...\$args) {\n";
    $lang .= "    return sprintf(__(\$key), ...\$args);\n";
    $lang .= "}\n";
    $lang .= "?>";
    
    return $lang;
}

function generateHtaccess() {
    $htaccess = "# BootPHP .htaccess Configuration\n";
    $htaccess .= "# Generated by installer on " . date('Y-m-d H:i:s') . "\n\n";
    
    // Enable rewrite engine
    $htaccess .= "RewriteEngine On\n\n";
    
    // Security headers
    $htaccess .= "# Security Headers\n";
    $htaccess .= "<IfModule mod_headers.c>\n";
    $htaccess .= "    Header always set X-Content-Type-Options nosniff\n";
    $htaccess .= "    Header always set X-Frame-Options DENY\n";
    $htaccess .= "    Header always set X-XSS-Protection \"1; mode=block\"\n";
    $htaccess .= "    Header always set Referrer-Policy \"strict-origin-when-cross-origin\"\n";
    $htaccess .= "    Header always set Permissions-Policy \"geolocation=(), microphone=(), camera=()\"\n";
    $htaccess .= "</IfModule>\n\n";
    
    // Hide sensitive files
    $htaccess .= "# Hide sensitive files\n";
    $htaccess .= "<FilesMatch \"\\.(htaccess|htpasswd|ini|log|sql|conf|config)$\">\n";
    $htaccess .= "    Order Allow,Deny\n";
    $htaccess .= "    Deny from all\n";
    $htaccess .= "</FilesMatch>\n\n";
    
    // Hide config directory
    $htaccess .= "# Protect config directory\n";
    $htaccess .= "RewriteRule ^config/ - [F,L]\n\n";
    
    // Hide logs directory
    $htaccess .= "# Protect logs directory\n";
    $htaccess .= "RewriteRule ^logs/ - [F,L]\n\n";
    
    // Hide installer directory (after installation)
    $htaccess .= "# Protect installer directory\n";
    $htaccess .= "RewriteRule ^installer/ - [F,L]\n\n";
    
    // Prevent access to PHP files in uploads
    $htaccess .= "# Prevent PHP execution in uploads\n";
    $htaccess .= "RewriteRule ^uploads/.*\\.php$ - [F,L]\n\n";
    
    // URL routing
    $htaccess .= "# URL Routing\n";
    $htaccess .= "RewriteCond %{REQUEST_FILENAME} !-f\n";
    $htaccess .= "RewriteCond %{REQUEST_FILENAME} !-d\n";
    $htaccess .= "RewriteRule ^(.*)$ index.php?route=$1 [QSA,L]\n\n";
    
    // Compression
    $htaccess .= "# Enable compression\n";
    $htaccess .= "<IfModule mod_deflate.c>\n";
    $htaccess .= "    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json\n";
    $htaccess .= "</IfModule>\n\n";
    
    // Cache control
    $htaccess .= "# Browser caching\n";
    $htaccess .= "<IfModule mod_expires.c>\n";
    $htaccess .= "    ExpiresActive on\n";
    $htaccess .= "    ExpiresByType text/css \"access plus 1 month\"\n";
    $htaccess .= "    ExpiresByType application/javascript \"access plus 1 month\"\n";
    $htaccess .= "    ExpiresByType image/png \"access plus 1 month\"\n";
    $htaccess .= "    ExpiresByType image/jpg \"access plus 1 month\"\n";
    $htaccess .= "    ExpiresByType image/jpeg \"access plus 1 month\"\n";
    $htaccess .= "    ExpiresByType image/gif \"access plus 1 month\"\n";
    $htaccess .= "    ExpiresByType image/svg+xml \"access plus 1 month\"\n";
    $htaccess .= "</IfModule>\n\n";
    
    // Error pages
    $htaccess .= "# Custom error pages\n";
    $htaccess .= "ErrorDocument 404 /error.php?code=404\n";
    $htaccess .= "ErrorDocument 403 /error.php?code=403\n";
    $htaccess .= "ErrorDocument 500 /error.php?code=500\n\n";
    
    return $htaccess;
}

function generateRobotsTxt() {
    $robots = "# robots.txt for BootPHP\n";
    $robots .= "# Generated by installer on " . date('Y-m-d H:i:s') . "\n\n";
    
    $robots .= "User-agent: *\n";
    $robots .= "Disallow: /config/\n";
    $robots .= "Disallow: /logs/\n";
    $robots .= "Disallow: /cache/\n";
    $robots .= "Disallow: /installer/\n";
    $robots .= "Disallow: /admin/\n";
    $robots .= "Disallow: /api/\n";
    $robots .= "Allow: /\n\n";
    
    $robots .= "# Sitemap location\n";
    $robots .= "Sitemap: " . getBaseUrl() . "/sitemap.xml\n";
    
    return $robots;
}

function generateMaintenancePage() {
    $maintenance = "<?php\n";
    $maintenance .= "/**\n";
    $maintenance .= " * BootPHP Maintenance Page\n";
    $maintenance .= " * Generated by installer on " . date('Y-m-d H:i:s') . "\n";
    $maintenance .= " */\n\n";
    
    $maintenance .= "// Check if maintenance mode is enabled\n";
    $maintenance .= "if (!defined('MAINTENANCE_MODE') || !MAINTENANCE_MODE) {\n";
    $maintenance .= "    header('Location: /');\n";
    $maintenance .= "    exit;\n";
    $maintenance .= "}\n\n";
    
    $maintenance .= "header('HTTP/1.1 503 Service Temporarily Unavailable');\n";
    $maintenance .= "header('Status: 503 Service Temporarily Unavailable');\n";
    $maintenance .= "header('Retry-After: 3600');\n";
    $maintenance .= "?>\n";
    $maintenance .= "<!DOCTYPE html>\n";
    $maintenance .= "<html lang=\"en\">\n";
    $maintenance .= "<head>\n";
    $maintenance .= "    <meta charset=\"UTF-8\">\n";
    $maintenance .= "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
    $maintenance .= "    <title>Site Maintenance - " . (defined('SITE_NAME') ? SITE_NAME : 'BootPHP') . "</title>\n";
    $maintenance .= "    <style>\n";
    $maintenance .= "        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; min-height: 100vh; display: flex; align-items: center; justify-content: center; }\n";
    $maintenance .= "        .container { text-align: center; max-width: 600px; padding: 2rem; }\n";
    $maintenance .= "        .icon { font-size: 4rem; margin-bottom: 1rem; }\n";
    $maintenance .= "        h1 { font-size: 2.5rem; margin-bottom: 1rem; }\n";
    $maintenance .= "        p { font-size: 1.2rem; margin-bottom: 2rem; opacity: 0.9; }\n";
    $maintenance .= "        .back-link { display: inline-block; padding: 0.75rem 1.5rem; background: rgba(255,255,255,0.2); border-radius: 0.5rem; text-decoration: none; color: white; transition: background 0.3s ease; }\n";
    $maintenance .= "        .back-link:hover { background: rgba(255,255,255,0.3); }\n";
    $maintenance .= "    </style>\n";
    $maintenance .= "</head>\n";
    $maintenance .= "<body>\n";
    $maintenance .= "    <div class=\"container\">\n";
    $maintenance .= "        <div class=\"icon\">🔧</div>\n";
    $maintenance .= "        <h1>Site Under Maintenance</h1>\n";
    $maintenance .= "        <p><?php echo defined('MAINTENANCE_MESSAGE') ? MAINTENANCE_MESSAGE : 'We are currently performing scheduled maintenance. Please check back soon.'; ?></p>\n";
    $maintenance .= "        <a href=\"#\" onclick=\"location.reload()\" class=\"back-link\">Refresh Page</a>\n";
    $maintenance .= "    </div>\n";
    $maintenance .= "</body>\n";
    $maintenance .= "</html>";
    
    return $maintenance;
}

function generateSecuritySalt() {
    return bin2hex(random_bytes(32));
}

// Helper function to get base URL during installation
function getBaseUrl() {
    $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $dir = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/');
    return $protocol . '://' . $host . $dir;
}
?>